### ISSUE TITLE
Podcasts Not Creating Feed

### ISSUE THREAD

**Issue by jayb54171** [sentriz/gonic#366] opened 2023-09-06 16:59 UTC
gonic version: v0.15.2
?docker tag: sentriz/gonic:latest?

I don't know if I am doing something wrong, but when I add a podcast URL I keep getting the following error:

`could not create feed: no audio in feed item`

I have other URLs (as example https://podcasts.files.bbci.co.uk/p029399x.rss) and they work and download to my directory.

The following links are not working for me:

- https://feeds.captivate.fm/cross-question-with-iain/
- https://feeds.captivate.fm/for-the-many/
- https://feeds.megaphone.fm/thefaultline
- https://feeds.captivate.fm/the-presidents-prime-ministers/
- https://feeds.acast.com/public/shows/031c2dcb-c66c-42b5-819e-2452031fe4f9

Some of the above links are rss feeds and some are HTML. 

Also is there plan to support OPML upload like playlist upload?

**Comment by BetaPictoris** [comment] 2023-09-06 18:09
The URLs aren't correct, this is often because the site you got them off of didn't link them correctly, or you're coming from an app that supported funky things.

The Captivate.fm podcasts seem to be directories, I'm assuming this is how they get those fancy previews(?), but they don't work with Gonic. You'll need to add `feed.xml` to the end so that you're referencing the file instead:

- https://feeds.captivate.fm/cross-question-with-iain/feed.xml
- https://feeds.captivate.fm/for-the-many/feed.xml
- https://feeds.captivate.fm/the-presidents-prime-ministers/feed.xml

Your Acast URL just redirects to a Megaphone one (`https://feeds.megaphone.fm/GLT4787413333`). As for the `megaphone.fm` URLs they both worked fine for me. Although, you can add `.xml` which *may* help:

- https://feeds.megaphone.fm/GLT4787413333.xml
- https://feeds.megaphone.fm/thefaultline.xml

**Comment by sentriz** [comment] 2023-09-06 18:30
yes, thanks @BetaPictoris :+1:

**Comment by jayb54171** [comment] 2023-09-06 18:39
@BetaPictoris @sentriz  Thank you for your fast response, I tried your suggestion, and I still get the same error as mentioned in my original post for all the URLs when I tested.

**Comment by sentriz** [comment] 2023-09-06 18:53
@jayb54171 for example `https://feeds.captivate.fm/cross-question-with-iain/feed.xml` is working for me

![image](https://github.com/sentriz/gonic/assets/6832539/d52bfac5-2273-44f6-bb21-f4418bbdb1e3)

**Comment by jayb54171** [comment] 2023-09-06 19:00
Yes, it adds to my list too, it creates a folder, it just doesn't download any content from the feeds like the others do. Not even the cover image.

![Screenshot 2023-09-06 205811](https://github.com/sentriz/gonic/assets/144053732/2868224c-2678-4764-a43d-7e0789d2c8c3)

**Comment by sentriz** [comment] 2023-09-06 21:31
ah i can reproduce this, and can confirm it's fixed by 19be6f0881ed6c0c3311793c55dbbbe0a5571f51 which can been in master since janurary, just not the latest release. you can try it now by upgrading to :nightly (make a backup of your database though, just in case)

otherwise hang on for the next release https://github.com/sentriz/gonic/milestone/2

**Closed by sentriz** 2023-09-06 21:31 UTC

**Comment by jayb54171** [comment] 2023-09-07 07:01
@sentriz @BetaPictoris  I updated to `:nightly` and I can confirm it is working, I had to remove my other podcasts and download all again (do you have plan to limit download?) as they didn't register for some reason or maybe I did something wrong but its not a problem for me. Thank you both for your help.
