### ISSUE TITLE
Missing getNowPlaying endpoint in API

### ISSUE THREAD

**Issue by dacagi** [sentriz/gonic#533] opened 2024-08-16 03:32 UTC
gonic version: v0.16.4
docker-tag: latest

Not sure if an issue or a feature request. I just noticed gonic is missing the getNowPlaying endpoint based on the Subsonic API [specification](https://www.subsonic.org/pages/api.jsp#getNowPlaying).

I was looking to integrate gonic in my Homepage dashboard by reusing their existing Navidrome widget. I expected them to be almost compatible to show some basic stats.

I found the definitions for the endpoints [here](https://github.com/sentriz/gonic/blob/master/server/ctrlsubsonic/ctrl.go) and was surprised to find so many options but not getNowPlaying.

Is this something that was missed somehow or did you decide to not include that specific endpoint?

**Comment by sentriz** [comment] 2024-08-16 09:56
hi, thanks for report. its a dupe of #510

**Closed** 2024-08-16 09:55 UTC
